from pathlib import Path
from sift_py.ingestion.channel import (
    ChannelBitFieldElement,
    ChannelConfig,
    ChannelDataType,
    ChannelEnumType,
)
from sift_py.ingestion.config.telemetry import FlowConfig, TelemetryConfig
from sift_py.ingestion.config.yaml.load import load_named_expression_modules
from sift_py.ingestion.rule.config import (
    RuleActionCreateDataReviewAnnotation,
    RuleConfig,
)

EXPRESSION_MODULES_DIR = Path().joinpath("expression_modules")

def vehicle_telemetry_config() -> TelemetryConfig:

    def motor_encoder_channel(motor: str) -> ChannelConfig:
        return ChannelConfig(
            name=f"motor_{motor}_encoder",
            data_type=ChannelDataType.INT_32,
            description=f"Hall encoder value for motor {motor}",
            component="mobility",
        )
        
    def motor_current_channel(motor: str) -> ChannelConfig:
        return ChannelConfig(
            name=f"motor_{motor}_current",
            data_type=ChannelDataType.DOUBLE,
            description=f"Current value for motor {motor}",
            unit="mA",
            component="mobility",
        )
        
    def motor_temp_channel(motor: str) -> ChannelConfig:
        return ChannelConfig(
            name=f"motor_{motor}_temperature",  # Ensure this matches what the Motor class outputs
            data_type=ChannelDataType.DOUBLE,
            description=f"Temperature value for motor {motor}",
            unit="C",
            component="mobility",
        )


    named_expressions = load_named_expression_modules(
        [
            EXPRESSION_MODULES_DIR.joinpath("kinematics.yml"),
            EXPRESSION_MODULES_DIR.joinpath("string.yml"),
        ]
    )

    # Define Channels
    log_channel = ChannelConfig(
        name="log",
        data_type=ChannelDataType.STRING,
        description="Vehicle logs",
    )

    # Motor channels
    # This will contain all 4 vehicle motors
    # hall encoder values
    # current values

    motor_a_encoder_channel = motor_encoder_channel("a")
    motor_b_encoder_channel = motor_encoder_channel("b")
    motor_c_encoder_channel = motor_encoder_channel("c")
    motor_d_encoder_channel = motor_encoder_channel("d")

    motor_a_current_channel = motor_current_channel("a")
    motor_b_current_channel = motor_current_channel("b")
    motor_c_current_channel = motor_current_channel("c")
    motor_d_current_channel = motor_current_channel("d")

    motor_a_temp_channel = motor_temp_channel("a")
    motor_b_temp_channel = motor_temp_channel("b")
    motor_c_temp_channel = motor_temp_channel("c")
    motor_d_temp_channel = motor_temp_channel("d")

    velocity_channel = ChannelConfig(
        name="velocity",
        data_type=ChannelDataType.DOUBLE,
        description="Vehicle speed",
        unit="Miles Per Hour",
        component="mainmotor",
    )
    voltage_channel = ChannelConfig(
        name="voltage",
        data_type=ChannelDataType.INT_32,
        description="Voltage at source",
        unit="Volts",
    )
    vehicle_state_channel = ChannelConfig(
        name="vehicle_state",
        data_type=ChannelDataType.ENUM,
        description="Vehicle state",
        enum_types=[
            ChannelEnumType(name="Idle", key=0),
            ChannelEnumType(name="Forward Drive", key=1),
            ChannelEnumType(name="Reverse Drive", key=2),
            ChannelEnumType(name="Fault", key=3),
        ],
    )
    gpio_channel = ChannelConfig(
        name="gpio",
        data_type=ChannelDataType.BIT_FIELD,
        description="GPIO pin states",
        bit_field_elements=[
            ChannelBitFieldElement(name="12v", index=0, bit_count=1),
            ChannelBitFieldElement(name="charge", index=1, bit_count=2),
            ChannelBitFieldElement(name="led", index=3, bit_count=4),
            ChannelBitFieldElement(name="heater", index=7, bit_count=1),
        ],
    )

    # Define Rules (optional, based on your needs)
    overheating_rule = RuleConfig(
        name="overheating",
        description="Checks for vehicle overheating",
        expression='$1 == "Forward Drive" && $2 > 80',
        channel_references=[
            {"channel_reference": "$1", "channel_identifier": vehicle_state_channel.fqn()},
            {"channel_reference": "$2", "channel_config": voltage_channel},
        ],
        action=RuleActionCreateDataReviewAnnotation(),
    )

    kinetic_energy_rule = RuleConfig(
        name="kinetic_energy",
        description="Tracks high energy output while in motion",
        expression=named_expressions["kinetic_energy_gt"],
        channel_references=[
            {"channel_reference": "$1", "channel_config": voltage_channel},
        ],
        sub_expressions={"$mass": 10, "$threshold": 470},
        action=RuleActionCreateDataReviewAnnotation(tags=["vehicle"]),
    )

    failure_rule = RuleConfig(
        name="failure",
        description="Checks for failures reported by logs",
        expression=named_expressions["log_substring_contains"],
        channel_references=[
            {"channel_reference": "$1", "channel_config": log_channel},
        ],
        sub_expressions={"$sub_string": "failure"},
        action=RuleActionCreateDataReviewAnnotation(tags=["vehicle", "failure"]),
    )

    # Define Flows
    return TelemetryConfig(
        asset_name="VehicleSimulation",
        ingestion_client_key="vehicle_simulation",
        rules=[overheating_rule, kinetic_energy_rule, failure_rule],
        flows=[
            FlowConfig(
                name="vehicle_10_hz",
                channels=[
                    velocity_channel,
                    vehicle_state_channel,
                    motor_a_encoder_channel,
                    motor_b_encoder_channel,
                    motor_c_encoder_channel,
                    motor_d_encoder_channel,
                    motor_a_current_channel,
                    motor_b_current_channel,
                    motor_c_current_channel,
                    motor_d_current_channel,
                    motor_a_temp_channel,
                    motor_b_temp_channel,
                    motor_c_temp_channel,
                    motor_d_temp_channel,
                ],
            ),
            FlowConfig(
                name="vehicle_50_hz",
                channels=[voltage_channel, gpio_channel],
            ),
            FlowConfig(
                name="readings",
                channels=[voltage_channel, vehicle_state_channel, gpio_channel],
            ),
            FlowConfig(name="voltage", channels=[voltage_channel]),
            FlowConfig(name="gpio_channel", channels=[gpio_channel]),
            FlowConfig(name="logs", channels=[log_channel]),
        ],
    )